services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: false
      DOMAIN: "http://testvaultwarden.local"  # Indiquez le domaine pour une configuration correcte
    ports:
      - 80:80  # Vaultwarden accepte les connexions HTTP internes
    volumes:
      - vw-data:/data

volumes:
  vw-data:
