name: Deploy Docker Services

on:
  push:
    branches:
      - main  # Exécuter sur chaque commit dans la branche main.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Étape 3 : Déployer les services Docker Compose
    - name: Deploy Docker Compose
      env:
        DOMAIN: ${{ secrets.DOMAIN }}       # Nom de domaine (via secrets)
        ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }} # Token administrateur (via secrets)
      run: |
        # Remplace les variables dans docker-compose.yml
        sed -i "s|YourDomain|$DOMAIN|g" docker-compose.yml
        sed -i "s|cf.Argon2section|$ADMIN_TOKEN|g" docker-compose.yml

        # Remplace les variables dans Caddyfile
        sed -i "s|*your domain name*|$DOMAIN|g" Caddyfile

        # Déployer les conteneurs Docker
        docker-compose up -d
