name: Deploy Docker Services

on:
  push:  # Déclenche le workflow à chaque commit pushé sur une branche spécifique
    branches:
      - main  # Remplacez "main" par le nom de la branche cible, si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Débogage (Lister les fichiers et répertoires)
    - name: Debug Files
      run: |
        ls -R DevOPS/Docker

    # Étape 3 : Remplacer les variables dans les fichiers
    - name: Update docker-compose.yml and Caddyfile
      env:
        DOMAIN: ${{ secrets.DOMAIN }}  # Domaine stocké comme secret GitHub
        ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}  # Token Admin stocké comme secret GitHub
      run: |
        # Remplace le domaine et le token dans docker-compose.yml
        sed -i "s|YourDomain|${DOMAIN}|g" DevOPS/Docker/docker-compose.yml
        sed -i "s|*your domain name*|${DOMAIN}|g" DevOPS/Docker/Caddyfile
        sed -i "s|cf.Argon2section|${ADMIN_TOKEN}|g" DevOPS/Docker/docker-compose.yml

    # Étape 4 : Déployer Docker Compose
    - name: Deploy Docker Compose
      run: |
        cd DevOPS/Docker
        docker-compose up -d
