name: Deploy Docker Services

on:
  workflow_dispatch:  # Permet de déclencher le workflow manuellement
    inputs:
      domain:  # Demande un input pour le domaine
        description: "Enter your domain (e.g., vault.example.com)"
        required: true
        default: "vault.example.com"
      admin_token:  # Demande un input pour le token admin
        description: "Enter your Admin Token"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Débogage (Lister les fichiers et répertoires)
    - name: Debug Files
      run: |
        ls -R DevOPS/Docker

    # Étape 3 : Remplacer les variables dans les fichiers
    - name: Update docker-compose.yml and Caddyfile
      run: |
        # Remplace le domaine dans docker-compose.yml et Caddyfile
        sed -i "s|YourDomain|${{ inputs.domain }}|g" DevOPS/Docker/docker-compose.yml
        sed -i "s|*your domain name*|${{ inputs.domain }}|g" DevOPS/Docker/Caddyfile
        sed -i "s|cf.Argon2section|${{ inputs.admin_token }}|g" DevOPS/Docker/docker-compose.yml

    # Étape 4 : Déployer Docker Compose
    - name: Deploy Docker Compose
      run: |
        cd DevOPS/Docker
        docker-compose up -d

